name = "d1-runtime-shim-test"
main = "src/worker.ts"
compatibility_date = "2023-07-10"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "new-shim-who-dis"
database_id = "9cd2ba39-6eca-4e30-9a2d-01e17664e57b"
